### ISSUE TITLE
请求mocker时，一直返回验证不通过

### ISSUE THREAD

**Issue by ziok2010** [DXY-F2E/api-mocker#10]
![image](https://user-images.githubusercontent.com/5848256/30904392-806f6114-a3a4-11e7-9fd6-d2180fc9fdaa.png)

如上图api接口的定义

通过postman打接口，如下图一直返回参数校验失败
![image](https://user-images.githubusercontent.com/5848256/30904472-a9ae2164-a3a4-11e7-8212-c2e766806543.png)

最奇怪的是，如果把接口定义的必选都去掉，就正常了！

不知道问题出在哪，烦请指教。

**Comment by wuomzfx** [comment]
勾选 x-www-form-urlencoded 试试，不过建议使用 json格式的提交。目前对form-data兼容不是非常好，而且form-data传到后台只能判断是 字符串类型，所以建议使用json格式提交，你这个问题，我这两天排查一下，有进展反馈到这个issue

**Comment by ziok2010** [comment]
![image](https://user-images.githubusercontent.com/5848256/30906004-0e33ee6c-a3a9-11e7-8806-abef1a4ac9db.png)
选择 x-www-form-urlencoded的时候，就会出现上图情况

**Comment by wuomzfx** [comment]
对，因为 form-data 传参，后台会认为是字符串，所以你这个 isAutoLogin在参数类型的校验上就失败了，所以建议还是用 json传输数据，或者暂时把 isAutoLogin参数类型调为 string

**Comment by ziok2010** [comment]
@wuomzfx  谢谢，按照您说的两种方式确实能解决问题。

对比目前一些开源的mocker平台，非常喜欢你们的项目。
我现在想要融入到团队的日常开发中，把老的项目的模拟数据都放到mocker平台上进行管理，但上述这种问题在体验上可能就会有些不便。

**Comment by wuomzfx** [comment]
谢谢肯定~你这个问题我这周找时间优化下，国庆前发一版

**Comment by wuomzfx** [comment]
fix in 5956d5d8fd1ce86b96b8c895caa19475aa7ba9ce
修复了 x-www-form-urlencoded 提交参数的校验，重新拉取下代码就好了，之前有个 配置文件 我也有调整，如果拉取过程中，配置文件有冲突，建议先备份一下自己的配置文件

**Comment by ziok2010** [comment]
好的，已经合并过去了，感谢。
