### ISSUE TITLE
mock如何生成一个随机时间，或随机的中文等？

### ISSUE THREAD

**Issue by hejingscu** [DXY-F2E/api-mocker#12]
众所周知
// example值为：
{
  "status|1-2": true,
  "number|1-100": 100
}
// 则会生成
{
  "status": false,
  "number": 40
}
那么如何生成一个随机时间？
是这样
{
  "time|Random.time()": ""
}
还是
{
  "time": Random.time()
}
上面两种方法都不行，生成的都是“Random.time()”字符串，期望得到的应该是一个随机时间，如"10:58:21"

**Comment by wuomzfx** [comment]
目前没有办法，系统随机数据能力依赖于 [mock.js](http://mockjs.com/)

**Comment by GooeyNyan** [comment]
去看 [mock.js的栗子](http://mockjs.com/examples.html) 🌰吧。

栗子:
- [时间的][Date]🌰

[Date]: http://mockjs.com/examples.html#Date

- [汉字的][Chinese]🌰

[Chinese]: http://mockjs.com/examples.html#Random.cparagraph(%20min?,%20max?%20)

```
{
    "time": "@date('yyyy-MM-dd HH:mm:ss')",
    "text": "@cparagraph(1, 3)"
}

// 生成
{
    "time": "1926-08-17 10:58:21",
    "text": "联道交林声各存委就出是最新单地市。层家运组度空约给才收验建任以研接东接。者保难对取文派类型便指海产。"
}
```

**Comment by JinboMa** [comment]
根据 mock.js 官方示例，已经可以解决该问题。
