### ISSUE TITLE
接口测试的时候出现跨域问题，可是后端已经开启跨域了

### ISSUE THREAD

**Issue by Ttxy0105** [DXY-F2E/api-mocker#15]
The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8080' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by wuomzfx** [comment]
你这个开启跨域的后端，不是指 api-mocker的服务端吧？api-mocker服务端默认就是开启跨域的

**Comment by Ttxy0105** [comment]
不是，是我们自己的服务端开启了跨域。我这边点击测试的时候，看console里面的报错好像是localhost不能去请求。有点疑问

**Comment by Ttxy0105** [comment]
用postman测试接口的时候，能成功

**Comment by wuomzfx** [comment]
@Ttxy0105 postman测试接口，本来也不会存在跨域问题的。http://oyrpdvj2f.bkt.clouddn.com/ 方便的话，你可以先在我这个测试的api-mocker系统里注册一个账号，再上面编辑下你们这个接口，我再去调试看看

**Comment by wuomzfx** [comment]
我大概知道原因了，你把服务端允许跨域关了，应该就好了，目前api-mocker的测试prod跟dev，还有代理模式的转发，都是服务端发起的代理请求，不需要服务端开启跨域的。不过你这开启跨域反而出问题，确实是个bug，我回头看看解决下。 @Ttxy0105

**Comment by Ttxy0105** [comment]
@wuomzfx 谢谢，最近也准备部署在服务器上，把公司的文档转到api-mocker上面

**Comment by wuomzfx** [comment]
@Ttxy0105 好，感谢反馈跟支持~

**Comment by Ttxy0105** [comment]
@wuomzfx 找到问题了

> 特别注意: 给一个带有withCredentials的请求发送响应的时候，服务器端必须指定允许请求的域名,不能使用“*”。上面这个例子中，如果响应头是这样的 Access-Control-Allow-Origin：* ，则响应会失败。[1](https://github.com/wengjq/Blog/issues/2)

我在testApi那个接口那边将`config.withCredentials`设置为`false`，就可以了。
全局的withCredentials导致了这个问题

**Comment by wuomzfx** [comment]
@Ttxy0105 不好意思，刚去测试链接上 看了下，不是我刚刚说的原因。请求结果成功了，只是你们返回的接口请求头是Content-Type:text/html; charset=utf-8，不是json格式的，解析失败了。你直接转发代理再去浏览器里打开其实是ok的。我看看怎么优化下这个错误提示，现在没catch对error

**Comment by wuomzfx** [comment]
@Ttxy0105 config.withCredentials 这个不能关，根本问题不是这里

**Comment by wuomzfx** [comment]
@Ttxy0105 另外，你们的接口我暂时拿来做下测试蛤。

**Comment by Ttxy0105** [comment]
@wuomzfx 但是`Access-Control-Allow-Origin:*` ，这边服务端是这么写的。
全局的withCredentials是给server端连接的，我之前设置全局withCredentials为false，导致我本地无法登录。之后我单独将testapi里面的config中的withCredentials设置为false，就可以了。
因为我这边没有设置`Access-Control-Allow-Origin`为某个确定地址的并且`Access-Control-Allow-Credentials:true`的接口可以测试，所以麻烦你啦

**Comment by wuomzfx** [comment]
@Ttxy0105 嗯，不过这应该是我在后端代理请求时做判断，我已经修改好传dev分支了，你可以拉取一下最新代码，重启下服务端就ok了，不需要客户端将withCredentials设为false。 fix in 7880cf60968388db15be2f2e2f10e6f84b697ddb .

**Comment by Ttxy0105** [comment]
@wuomzfx 好的，辛苦啦。
请教下：可以部署在windows的服务器上吗？

**Comment by wuomzfx** [comment]
@Ttxy0105 我没有尝试过，应该是没问题的，有问题可以随时跟我说，github没反应的话，可以加我微信，75851654
