### ISSUE TITLE
优化Nginx配置

### ISSUE THREAD

**Issue by MiderWong** [DXY-F2E/api-mocker#23]
假设api-mocker项目文件夹路径为`__api_mocker_path`，网络域名为`your-mocker.com`，
官方给的Nginx配置，需要访问`http://your-mocker.com/mock`，一般情况下，为了方便，都是直接访问域名，可以修改Nginx配置如下：
1、
```
server {
        listen       80;
        server_name  your-mocker.com;
        root   __api_mocker_path/client/dist;
        index  index.html;

        location /mock-api/ {
            proxy_pass http://127.0.0.1:7001/;
        }
}

```
2、修改`client/config/index.js`文件下的serverRoot，改为`your-mocker.com/mock-api`
3、访问`your-mocker.com`

希望予以采纳。

**Comment by wuomzfx** [comment]
nginx这里只是简单的举个示例， 具体怎么配置都没关系啦。

我的demo页 http://api-mocker.com 中静态文件 直接部署到了 cdn。然后 服务端 配了 单独的二级域名 server.api-mocker.com。

**Comment by MiderWong** [comment]
嗯嗯，明白。
