### ISSUE TITLE
mongod安全模式问题

### ISSUE THREAD

**Issue by MiderWong** [DXY-F2E/api-mocker#27]
使用安全模式启动`MongoDB`(mongod --auth)后，修改`server/config/config.default.js`中的`mongoose`内容，原内容：
```
mongoose: {
     url: 'mongodb://127.0.0.1/apimock'
 }
```
修改后的内容：
```
mongoose: {
        url: 'mongodb://apimock:apimockPwd@127.0.0.1/apimock'
 }
```
重新启动server，提示`登录失败：undefined`，是不能使用安全模式启动MongoDB么？

**Comment by wuomzfx** [comment]
可以的，请确认数据库名、密码、端口号是否正确，比如我默认数据库是api-mock

**Comment by MiderWong** [comment]
恩，确实是可以的，因为密码中有特殊字符，所以需要转码才可以，不是程序的问题
