### ISSUE TITLE
请求测试和线上一直提示Internal Server Error

### ISSUE THREAD

**Issue by dreamsky** [DXY-F2E/api-mocker#34]

**Comment by wuomzfx** [comment]
先核对下地址是不是绝对路径，然后再核对下 地址 是否确实真实可访问

**Comment by wuomzfx** [comment]
api-mocker.com 的那个地址是吧，好像是有问题，我等下去排查下

**Comment by wuomzfx** [comment]
@dreamsky http://api-mocker.com 上给个示例看看

**Comment by dreamsky** [comment]
@wuomzfx 用了你们网站一个例子哈
http://api-mocker.com/#/edit/5a67284f83bb81687f750a07/5a67e634866016688538df97

**Comment by wuomzfx** [comment]
@dreamsky 看了下，主要是因为请求头跟返回头一起约束不一致导致的。
比如上面这个示例，直接配置成代理模式，请求mock地址是ok的，但是在api-mocker.com上通过测试进行代理转发不行。因为请求头要求接受json，但返回头又指定text，再加上content-length不一致，就500了。
建议自己约定一下客户端与服务端的请求头一致，应该就ok了。我发个dev，将content-length删去，但是其他请求头我还是先不删了，因为可能就是有特殊需求的。 027ad7d3c8f3830735ff664d9f2dfb22d981312e

**Comment by dreamsky** [comment]
@wuomzfx 👍 响应很及时！感谢！
