### ISSUE TITLE
优化api查询，希望支持分组管理接口

### ISSUE THREAD

**Issue by ghost** [DXY-F2E/api-mocker#38]
使用中遇到的问题：
1.api文档加载慢
2.文档在查看状态，再次编辑无法保存
3.希望可以进行多级分组管理用户和接口

**Comment by wuomzfx** [comment]
1. 文档加载慢，请问该组共有多少接口了呢？
2. 第二点无法保存可以具体描述错误信息么？或者截图看看
3. 多级分组短期内应该不会有计划。
