### ISSUE TITLE
接口列表界面 右边出来滚动条的时候 界面狂抖

### ISSUE THREAD

**Issue by dadianzi** [DXY-F2E/api-mocker#53]
接口列表界面 右边出来滚动条的时候 界面狂抖 根本停不下来

**Comment by pzljp** [comment]
定位一下出现滚动条的元素，加一个overflow: hidden就可以了

**Comment by pzljp** [comment]
欢迎加群反馈
![image](https://user-images.githubusercontent.com/5746654/61603654-07950780-ac71-11e9-838f-d31060c7f6e4.png)
