### ISSUE TITLE
response有必填字段 保存时报错{"message":"’data.name‘: required;’data.age‘: required"}

### ISSUE THREAD

**Issue by pandaXiong01** [DXY-F2E/api-mocker#55]
报错信息
![23_06_07__08_19_2019](https://user-images.githubusercontent.com/13148696/63276942-fa525380-c2d6-11e9-85ab-978a0c45ea15.jpg)
{"message":"’data.name‘: required;’data.age‘: required"}

**Comment by pzljp** [comment]
既然是response的必填字段，在设置example的时候，data.name、data.age也是要有的。
