### ISSUE TITLE
如何进行接口测试

### ISSUE THREAD

**Issue by webdq** [DXY-F2E/api-mocker#56]
其他功能点
· 接口测试。开发人员可以在系统上直接测试接口，避免在postman等请求工具上又填写众多参数

创建接口后，没有地方进行接口测试啊，怎么测试接口？

**Comment by pzljp** [comment]
很好的建议，近期会考虑加上。现在都是用postman、charles等工具拼接请求来测试接口

**Comment by lusq010** [comment]
main分支的新版本中已添加该feature
