### ISSUE TITLE
资源请求失败

### ISSUE THREAD

**Issue by FatDoge** [DXY-F2E/api-mocker#60]
**问题描述**
隔一段时间就会出现白屏一直加载的情况，查看network发现是一个```vendor.js```请求时间超长，一直请求到分钟级别而后控制台报错```net::ERR_CONNECTION_RESET 200```

**尝试过的措施**
- [x] 服务端```nginx```重启
- [x] 服务端```pm2```重启
- [x] 服务端项目根目录```make install```重新启动```mongodb```
> 最后一步有效，但是该问题周期性出现，不知道根源在哪。

**Comment by lusq010** [comment]
未复现。
