### ISSUE TITLE
关于 Mock 生成的 Url  

### ISSUE THREAD

**Issue by Hucy** [DXY-F2E/api-mocker#7]
##  感谢作者提供这么好的工具，有个问题想请教下：
mock 生成的url 是不确定，这个就导致我在开发的过程中不能和后端的api保持一致，
更倾向于 一个接口分组下的 生成的 mock 地址是可以 自己配置的:
` group_basic_url/customize_url`
这样就可以保证 之前代码的接口地址不做改动也能很好整合。

**Comment by wuomzfx** [comment]
嗯，一直有考虑，就是没找到比较好的交互方式来添加这个功能，同时还需要考虑接口url重复等带来的问题，我最近找时间看看，尽快加上这个功能。谢谢您的反馈~

**Comment by includeleec** [comment]
线上地址、测试地址可以写个map文件对应起来。

**Comment by wuomzfx** [comment]
对的，我这边目前就是自己有专门的文件负责暴露接口，根据环境判断选取测试地址、线上地址、mock地址

**Comment by wuomzfx** [comment]
如果有在部署使用的话，欢迎加入api mocker使用交流群~

![wechatimg193](https://user-images.githubusercontent.com/8017237/30808865-651e6fc6-a1c5-11e7-98a7-2d21cd45b649.jpeg)

**Comment by thecreation** [comment]
二维码过期了。求更新。

**Comment by wuomzfx** [comment]
@amazingSurge 已更新

**Comment by heibai01** [comment]
这个提议也是我想说的。交互方式可以参照postman，有个全局变量的设置。
比如我的接口地址是：{{project_domain}}/users
project_domain 对应几个值，比如Mock服务地址、Test地址、Production地址

**Comment by heibai01** [comment]
然后是迫切希望增加一个请求方式：PATCH。
* PATCH一般用于资源的部分更新，而PUT一般用于资源的整体更新。
* 当资源不存在时，PATCH会创建一个新的资源，而PUT只会对已在资源进行更新。

甚至可以加更多，照HTTP协议加。。。

**Comment by wuomzfx** [comment]
@heibai01 增加patch了， 5956d5d8fd1ce86b96b8c895caa19475aa7ba9ce
重新拉取下代码就好了，之前有个 配置文件 我也有调整，如果拉取过程中，配置文件有冲突，建议先备份一下自己的配置文件

**Comment by helloxdan** [comment]
随机生成的url，客户端调用这样一个没有标识意义的字符串，很难管理啊。有解决方案了没？

**Comment by wuomzfx** [comment]
@helloxdan 目前还没有，如果您在这方面有急迫的需求话，可以自己定制一下，请求特定的mock地址加上参数，如：http://api-mocker.com/mock-data?url=/module1/api1    ,然后mocker后端根据这个`url`参数对数据库中的api 的线上地址 和 测试地址 进行模糊匹配，获取到第一个 接口即为 mock接口 ，然后执行后续操作

**Comment by lusq010** [comment]
main分支新版本中已强化了api路径的概念，通过 应用（hash） + 接口路径 + 请求方法 作为api唯一标识，从而解决mock api与真实接口路径不一致的问题，调用方在同一应用中调用不同环境的api只需要切换不同的baseUrl即可；同时解决了hash模式下api语义丢失问题
