### ISSUE TITLE
使用nginx部署好了，没报错，但是页面空白

### ISSUE THREAD

**Issue by includeleec** [DXY-F2E/api-mocker#8]
![image](https://user-images.githubusercontent.com/3683190/30587054-7085fdb2-9d64-11e7-84bb-be5117d307a7.png)

**Comment by wuomzfx** [comment]
最后一个请求没结束，可能是服务端没配好

**Comment by includeleec** [comment]
可以了！感谢！
对了，管理员角色账号密码是多少？

**Comment by wuomzfx** [comment]
目前并没有超级管理员，谁建的接口与分组，只能由他负责
