### ISSUE TITLE
启动之后mongo报错

### ISSUE THREAD

**Issue by Cuihongsen** [DXY-F2E/api-mocker#9]
DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

**Comment by wuomzfx** [comment]
请具体描述下是哪个过程发生的错误

**Comment by Cuihongsen** [comment]
server在服务器上启动之后，注册账号的时候api返回 `{"code":13,"message":"Internal Server Error"}`
在服务器的输出是`(node:23034) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html` 然后就没有了

**Comment by wuomzfx** [comment]
这个mongoose的警告应该不会导致程序挂了，至于注册帐号返回服务器错误，我目前没办法复现，你看看有没有其他信息可以提供，或者有node能力的话，可以去 `server/app/controller/user.js`路径下调试下`create`方法看看
